package house.spring.vote.domain.model

enum class SortBy {
    CREATED_AT,
    VOTE_COUNT,
    COMMENT_COUNT,
    RECENTLY_UPDATED_AT,
    RECENTLY_VOTED_AT,
    RECENTLY_COMMENTED_AT,
    RECENTLY_CREATED_AT,
    RECENTLY_VOTED_COMMENTED_AT,
    RECENTLY_VOTED_CREATED_AT,
    RECENTLY_COMMENTED_CREATED_AT,
    RECENTLY_VOTED_COMMENTED_CREATED_AT
}